# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "xhci_pci"
        "ahci"
        "usb_storage"
        "usbhid"
        "sd_mod"
        "nfs"
      ];
      kernelModules = [ ];
    };
    kernelModules = [
      "kvm-amd"
      "kvm-intel"
      "kvm"
    ];
    extraModulePackages = [ ];
    supportedFilesystems = [ "nfs" ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/af2f8af9-f207-491a-8c3c-a734e7f2917e";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/3095-1960";
      fsType = "vfat";
      options = [
        "fmask=0022"
        "dmask=0022"
      ];
    };

    "/data" = {
      device = "/dev/disk/by-uuid/ad9c7904-29df-474d-8de4-8d93137e06b9";
      fsType = "ext4";
    };

    "/home/franky/games" = {
      device = "/dev/disk/by-uuid/4b0344e8-255f-4709-9e76-7e7b499d5521";
      fsType = "ext4";
    };

    "/home/franky/games2" = {
      device = "/dev/disk/by-uuid/442159ec-9409-420b-ba62-6c0d08b6e2f8";
      fsType = "ext4";
    };

    "/mnt/NAS" = {
      device = "192.168.0.33:/mnt/user/Babylon";
      fsType = "nfs";
    };
  };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp8s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware = {
    cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    nvidia.package = config.boot.kernelPackages.nvidiaPackages.beta;
    bluetooth = {
      enable = true;
      powerOnBoot = true;
    };
  };
}
