{
  pkgs,
  lib,
  vars,
  config,
  inputs,
  ...
}:
let
  m = vars;
  workspaceMappings = {
    "1" = m.tertiaryMonitor.name;
    "2" = m.mainMonitor.name;
    "3" = m.secondaryMonitor.name;
    "4" = m.tertiaryMonitor.name;
    "5" = m.mainMonitor.name;
    "6" = m.secondaryMonitor.name;
    "7" = m.tertiaryMonitor.name;
    "8" = m.mainMonitor.name;
    "9" = m.secondaryMonitor.name;
    "10" = m.fourthMonitor.name;
    "99" = "HEADLESS-1";
  };

  # A/B switch for the Samsung TV (fourthMonitor). Its EDID advertises no
  # 3840x2160@60 -- only 4K at 30 Hz or below -- so the real choice is sharpness
  # (4K30) vs. smoothness (1080p60), and which one wins is a feel question the
  # config can't answer. `tv-mode 4k` / `tv-mode 1080` flips it live through
  # hyprctl, no rebuild and no logout. Once one of them clearly wins, copy its
  # numbers into vars.nix:fourthMonitor to make it the boot default.
  #
  # If Input Signal Plus ever gets enabled on that HDMI input, the TV should
  # start advertising 4K60 and this whole tradeoff goes away.
  tvMode = pkgs.writeShellScriptBin "tv-mode" ''
    set -euo pipefail
    out="${m.fourthMonitor.name}"
    case "''${1:-}" in
      4k)   mode="3840x2160@30"; pos="7180x0" ;;
      1080) mode="1920x1080@60"; pos="8140x1080" ;;
      *) echo "usage: tv-mode 4k|1080" >&2; exit 2 ;;
    esac
    hyprctl eval "hl.monitor({ output = \"$out\", mode = \"$mode\", position = \"$pos\", scale = 1 })" >/dev/null
    hyprctl monitors -j | ${pkgs.jq}/bin/jq -r '
      .[] | select(.description | test("SAMSUNG"))
      | "\(.name) now \(.width)x\(.height)@\(.refreshRate|round) at \(.x)x\(.y)"'
  '';
in
{
  imports = [
    ../../_features/hydra-smb.nix
    ../../_features/hermes-desktop.nix
  ];

  hydra-smb.enable = true;
  hermesDesktop.enable = true;

  hyprland.workspaceRecovery = {
    enable = true;
    mappings = workspaceMappings;
  };

  home.packages = [
    inputs.llm.packages.${pkgs.system}.cursor-agent
    tvMode
  ];

  mpv-mod.plexShim.enable = true;

  xdg.configFile."hypr/hyprland.conf" = {
    force = true;
    text = ''
      autogenerated = 1
    '';
  };

  wayland.windowManager.hyprland.extraConfig = lib.mkAfter ''
    -- == Cerberus monitors ==
    hl.monitor({ output = "${m.tertiaryMonitor.name}", mode = "${toString m.tertiaryMonitor.width}x${toString m.tertiaryMonitor.height}@${toString m.tertiaryMonitor.refresh}", position = "5900x2160", scale = 1 })
    hl.monitor({ output = "${m.mainMonitor.name}",     mode = "${toString m.mainMonitor.width}x${toString m.mainMonitor.height}@${toString m.mainMonitor.refresh}",         position = "7820x2160", scale = 1 })
    hl.monitor({ output = "${m.secondaryMonitor.name}", mode = "${toString m.secondaryMonitor.width}x${toString m.secondaryMonitor.height}@${toString m.secondaryMonitor.refresh}", position = "10380x2160", scale = 1 })
    hl.monitor({ output = "${m.fourthMonitor.name}",   mode = "${toString m.fourthMonitor.width}x${toString m.fourthMonitor.height}@${toString m.fourthMonitor.refresh}",     position = "7180x0",  scale = 1 })
    hl.monitor({ output = "HEADLESS-1", mode = "2160x1440@60", position = "auto", scale = 1 })

    -- == Cerberus workspace pins ==
    hl.workspace_rule({ workspace = "1",  monitor = "${m.tertiaryMonitor.name}",  default = true })
    hl.workspace_rule({ workspace = "2",  monitor = "${m.mainMonitor.name}",      default = true })
    hl.workspace_rule({ workspace = "3",  monitor = "${m.secondaryMonitor.name}", default = true })
    hl.workspace_rule({ workspace = "4",  monitor = "${m.tertiaryMonitor.name}" })
    hl.workspace_rule({ workspace = "5",  monitor = "${m.mainMonitor.name}" })
    hl.workspace_rule({ workspace = "6",  monitor = "${m.secondaryMonitor.name}" })
    hl.workspace_rule({ workspace = "7",  monitor = "${m.tertiaryMonitor.name}" })
    hl.workspace_rule({ workspace = "8",  monitor = "${m.mainMonitor.name}" })
    hl.workspace_rule({ workspace = "9",  monitor = "${m.secondaryMonitor.name}" })
    hl.workspace_rule({ workspace = "10", monitor = "${m.fourthMonitor.name}",    default = true })
    hl.workspace_rule({ workspace = "99", monitor = "HEADLESS-1",                 default = true })

    -- == Cerberus env ==
    hl.env("LIBVA_DRIVER_NAME", "nvidia")
    hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
    hl.env("NVD_BACKEND", "direct")
    hl.env("XDG_SESSION_TYPE", "wayland")
    hl.env("GBM_BACKEND", "nvidia-drm")
    hl.env("__GL_GSYNC_ALLOWED", "1")
    hl.env("__GL_VRR_ALLOWED", "1")
    hl.env("WLR_NO_HARDWARE_CURSORS", "1")
    hl.env("NIXOS_OZONE_WL", "1")
    hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
    hl.env("QT_QPA_PLATFORM", "wayland;xcb")
    hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
    hl.env("XDG_SESSION_DESKTOP", "Hyprland")
    hl.env("XDG_CONFIG_HOME", "${config.xdg.configHome}")
    hl.env("BROWSER", "Firefox")
    hl.env("GTK_USE_PORTAL", "1")
    hl.env("XCURSOR_SIZE", "22")
    hl.env("EDITOR", "nvim")
    -- == Cerberus overrides (VRR, cursor, ecosystem) ==
    hl.config({
      misc = {
        vrr = 2,
      },
      cursor = {
        no_hardware_cursors = true,
      },
      ecosystem = {
        no_update_news = true,
        no_donation_nag = true,
      },
    })

    -- == Cerberus startup ==
    hl.on("hyprland.start", function()
      hl.exec_cmd("systemctl --user start gnome-keyring.service")
      hl.exec_cmd("systemctl --user start gvfs-daemon.service")
      hl.exec_cmd("dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_RUNTIME_DIR DBUS_SESSION_BUS_ADDRESS SSH_AUTH_SOCK && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target")
      hl.exec_cmd("${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1")
      hl.exec_cmd("hyprctl output create headless HEADLESS-1")
      hl.exec_cmd("blueman-applet")
      -- GVfs Hydra mount after keyring (restores pre-2e9e10b hypr.nix session ordering)
      hl.exec_cmd("systemctl --user start mount-hydra.service")
    end)
  '';

  services.hyprpaper.settings = {
    preload = lib.mkForce [ vars.wallpaper ];
    wallpaper = lib.mkForce [
      "${vars.mainMonitor.name},${vars.wallpaper}"
      "${vars.secondaryMonitor.name},${vars.wallpaper}"
      "${vars.tertiaryMonitor.name},${vars.wallpaper}"
      "${vars.fourthMonitor.name},${vars.wallpaper}"
    ];
  };
}
